version: '3.8'

services:
  mariadb:
    image: mariadb:10.6
    container_name: webkareerfit-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: kareerfit_webapp
      MYSQL_USER: kareerfit_webapp
      MYSQL_PASSWORD: ZaqXsw123ZaqXsw123
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mariadb_data:
