name = "webkareerfit"
main = ".next/standalone/server.js"
compatibility_date = "2025-08-22"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[[routes]]
pattern = "my.kareerfit.com"
custom_domain = true

[env.production]
name = "webkareerfit-prod"
route = "my.kareerfit.com/*"
