[pages]
workers_dev = true
compatibility_date = "2025-08-22"
compatibility_flags = ["nodejs_compat"]

[pages.build]
command = "npm run build"
output_dir = ".next"

[pages.preview]
host = "my.kareerfit.com"
